import { Position } from "@xyflow/react";
import {
  Battery,
  Lightbulb,
  CircleDot,
  Cpu,
  Volume2,
  Fan,
  Gauge,
  Monitor,
  Hash,
  type LucideIcon,
} from "lucide-react";

/**
 * Handle/Pin configuration for node connection points
 */
export interface HandleConfig {
  id: string;
  type: "source" | "target";
  position: Position;
  label: string;
  dataType: "execution" | "object" | "value" | "boolean" | "vector";
  offsetPercentage?: number; // Percentage from top (0-100)
  description?: string; // Optional description shown in tooltip
}

/**
 * Complete node configuration
 */
export interface NodeConfig {
  type: string;
  title: string;
  subtitle?: string;
  icon: LucideIcon;
  handles: HandleConfig[];
  width?: number;
  height?: number;
}

/**
 * Data type to color mapping for handles
 */
export const handleColors: Record<HandleConfig["dataType"], string> = {
  execution: "#ffffff",
  object: "#3b82f6", // blue-500
  value: "#f59e0b", // amber-500
  boolean: "#10b981", // emerald-500
  vector: "#8b5cf6", // violet-500
};

/**
 * Battery Node Configuration
 */
export const batteryNodeConfig: NodeConfig = {
  type: "battery",
  title: "Battery",
  subtitle: "Power Source",
  icon: Battery,
  handles: [
    {
      id: "plus",
      type: "source",
      position: Position.Right,
      label: "+",
      dataType: "value",
      offsetPercentage: 35,
      description: "Positive terminal - connects to power input",
    },
    {
      id: "minus",
      type: "source",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 65,
      description: "Negative terminal - ground reference",
    },
  ],
  width: 180,
  height: 100,
};

/**
 * LED Node Configuration
 */
export const ledNodeConfig: NodeConfig = {
  type: "led",
  title: "LED",
  subtitle: "Light Emitter",
  icon: Lightbulb,
  handles: [
    {
      id: "anode",
      type: "target",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 35,
      description: "Anode - positive terminal (longer leg)",
    },
    {
      id: "anode",
      type: "source",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 35,
      description: "Anode - positive terminal (longer leg)",
    },
    {
      id: "cathode",
      type: "target",
      position: Position.Left,
      label: "-",
      dataType: "value",
      offsetPercentage: 65,
      description: "Cathode - negative terminal (shorter leg)",
    },
    {
      id: "cathode",
      type: "source",
      position: Position.Left,
      label: "-",
      dataType: "value",
      offsetPercentage: 65,
      description: "Cathode - negative terminal (shorter leg)",
    },
  ],
  width: 180,
  height: 120,
};

/**
 * Button Node Configuration
 */
export const buttonNodeConfig: NodeConfig = {
  type: "button",
  title: "Button",
  subtitle: "Switch Control",
  icon: CircleDot,
  handles: [
    {
      id: "in",
      type: "target",
      position: Position.Left,
      label: "In",
      dataType: "value",
      offsetPercentage: 50,
      description: "Input connection - receives current",
    },
    {
      id: "out",
      type: "source",
      position: Position.Right,
      label: "Out",
      dataType: "value",
      offsetPercentage: 50,
      description: "Output connection - active when button is pressed",
    },
  ],
  width: 180,
  height: 100,
};

/**
 * Arduino Uno Node Configuration
 */
export const arduinoUnoNodeConfig: NodeConfig = {
  type: "arduino-uno",
  title: "Arduino Uno",
  subtitle: "Microcontroller",
  icon: Cpu,
  handles: [
    // Power/Control pins (Left side)
    {
      id: "vin",
      type: "source",
      position: Position.Left,
      label: "VIN",
      dataType: "value",
      offsetPercentage: 55,
      description: "External power input (7-12V recommended)",
    },
    {
      id: "vin",
      type: "target",
      position: Position.Left,
      label: "VIN",
      dataType: "value",
      offsetPercentage: 55,
      description: "External power input (7-12V recommended)",
    },
    {
      id: "5v",
      type: "source",
      position: Position.Left,
      label: "5V",
      dataType: "value",
      offsetPercentage: 40,
      description: "Regulated 5V power output",
    },
    {
      id: "5v",
      type: "target",
      position: Position.Left,
      label: "5V",
      dataType: "value",
      offsetPercentage: 40,
      description: "Regulated 5V power output",
    },
    {
      id: "3v3",
      type: "source",
      position: Position.Left,
      label: "3.3V",
      dataType: "value",
      offsetPercentage: 35,
      description: "Regulated 3.3V power output (max 50mA)",
    },
    {
      id: "3v3",
      type: "target",
      position: Position.Left,
      label: "3.3V",
      dataType: "value",
      offsetPercentage: 35,
      description: "Regulated 3.3V power output (max 50mA)",
    },
    {
      id: "gnd1",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 50,
      description: "Ground reference - connect to circuit ground",
    },
    {
      id: "gnd1",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 50,
      description: "Ground reference - connect to circuit ground",
    },
    {
      id: "gnd2",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 45,
      description: "Ground reference - connect to circuit ground",
    },
    {
      id: "gnd2",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 45,
      description: "Ground reference - connect to circuit ground",
    },
    {
      id: "reset",
      type: "source",
      position: Position.Left,
      label: "RST",
      dataType: "value",
      offsetPercentage: 30,
      description: "Reset the microcontroller (active LOW)",
    },
    {
      id: "reset",
      type: "target",
      position: Position.Left,
      label: "RST",
      dataType: "value",
      offsetPercentage: 30,
      description: "Reset the microcontroller (active LOW)",
    },
    {
      id: "aref",
      type: "source",
      position: Position.Left,
      label: "AREF",
      dataType: "value",
      offsetPercentage: 25,
      description: "Analog reference voltage for ADC",
    },
    {
      id: "aref",
      type: "target",
      position: Position.Left,
      label: "AREF",
      dataType: "value",
      offsetPercentage: 25,
      description: "Analog reference voltage for ADC",
    },

    // Analog pins (Left)
    {
      id: "a0",
      type: "source",
      position: Position.Left,
      label: "A0",
      dataType: "value",
      offsetPercentage: 65,
      description: "Analog input 0 (10-bit ADC, 0-5V)",
    },
    {
      id: "a0",
      type: "target",
      position: Position.Left,
      label: "A0",
      dataType: "value",
      offsetPercentage: 65,
      description: "Analog input 0 (10-bit ADC, 0-5V)",
    },
    {
      id: "a1",
      type: "source",
      position: Position.Left,
      label: "A1",
      dataType: "value",
      offsetPercentage: 70,
      description: "Analog input 1 (10-bit ADC, 0-5V)",
    },
    {
      id: "a1",
      type: "target",
      position: Position.Left,
      label: "A1",
      dataType: "value",
      offsetPercentage: 70,
      description: "Analog input 1 (10-bit ADC, 0-5V)",
    },
    {
      id: "a2",
      type: "source",
      position: Position.Left,
      label: "A2",
      dataType: "value",
      offsetPercentage: 75,
      description: "Analog input 2 (10-bit ADC, 0-5V)",
    },
    {
      id: "a2",
      type: "target",
      position: Position.Left,
      label: "A2",
      dataType: "value",
      offsetPercentage: 75,
      description: "Analog input 2 (10-bit ADC, 0-5V)",
    },
    {
      id: "a3",
      type: "source",
      position: Position.Left,
      label: "A3",
      dataType: "value",
      offsetPercentage: 80,
      description: "Analog input 3 (10-bit ADC, 0-5V)",
    },
    {
      id: "a3",
      type: "target",
      position: Position.Left,
      label: "A3",
      dataType: "value",
      offsetPercentage: 80,
      description: "Analog input 3 (10-bit ADC, 0-5V)",
    },
    {
      id: "a4",
      type: "source",
      position: Position.Left,
      label: "A4",
      dataType: "value",
      offsetPercentage: 85,
      description: "Analog input 4 (10-bit ADC, 0-5V) - also I2C SDA",
    },
    {
      id: "a4",
      type: "target",
      position: Position.Left,
      label: "A4",
      dataType: "value",
      offsetPercentage: 85,
      description: "Analog input 4 (10-bit ADC, 0-5V) - also I2C SDA",
    },
    {
      id: "a5",
      type: "source",
      position: Position.Left,
      label: "A5",
      dataType: "value",
      offsetPercentage: 90,
      description: "Analog input 5 (10-bit ADC, 0-5V) - also I2C SCL",
    },
    {
      id: "a5",
      type: "target",
      position: Position.Left,
      label: "A5",
      dataType: "value",
      offsetPercentage: 90,
      description: "Analog input 5 (10-bit ADC, 0-5V) - also I2C SCL",
    },

    // Digital pins (Right side)
    {
      id: "d0",
      type: "source",
      position: Position.Right,
      label: "D0",
      dataType: "value",
      offsetPercentage: 90,
      description: "Digital I/O pin 0 - also Serial RX",
    },
    {
      id: "d0",
      type: "target",
      position: Position.Right,
      label: "D0",
      dataType: "value",
      offsetPercentage: 90,
      description: "Digital I/O pin 0 - also Serial RX",
    },
    {
      id: "d1",
      type: "source",
      position: Position.Right,
      label: "D1",
      dataType: "value",
      offsetPercentage: 85,
      description: "Digital I/O pin 1 - also Serial TX",
    },
    {
      id: "d1",
      type: "target",
      position: Position.Right,
      label: "D1",
      dataType: "value",
      offsetPercentage: 85,
      description: "Digital I/O pin 1 - also Serial TX",
    },
    {
      id: "d2",
      type: "source",
      position: Position.Right,
      label: "D2",
      dataType: "value",
      offsetPercentage: 80,
      description: "Digital I/O pin 2 - supports interrupts",
    },
    {
      id: "d2",
      type: "target",
      position: Position.Right,
      label: "D2",
      dataType: "value",
      offsetPercentage: 80,
      description: "Digital I/O pin 2 - supports interrupts",
    },
    {
      id: "d3",
      type: "source",
      position: Position.Right,
      label: "D3",
      dataType: "value",
      offsetPercentage: 75,
      description: "Digital I/O pin 3 - PWM enabled, supports interrupts",
    },
    {
      id: "d3",
      type: "target",
      position: Position.Right,
      label: "D3",
      dataType: "value",
      offsetPercentage: 75,
      description: "Digital I/O pin 3 - PWM enabled, supports interrupts",
    },
    {
      id: "d4",
      type: "source",
      position: Position.Right,
      label: "D4",
      dataType: "value",
      offsetPercentage: 70,
      description: "Digital I/O pin 4",
    },
    {
      id: "d4",
      type: "target",
      position: Position.Right,
      label: "D4",
      dataType: "value",
      offsetPercentage: 70,
      description: "Digital I/O pin 4",
    },
    {
      id: "d5",
      type: "source",
      position: Position.Right,
      label: "D5",
      dataType: "value",
      offsetPercentage: 65,
      description: "Digital I/O pin 5 - PWM enabled",
    },
    {
      id: "d5",
      type: "target",
      position: Position.Right,
      label: "D5",
      dataType: "value",
      offsetPercentage: 65,
      description: "Digital I/O pin 5 - PWM enabled",
    },
    {
      id: "d6",
      type: "source",
      position: Position.Right,
      label: "D6",
      dataType: "value",
      offsetPercentage: 60,
      description: "Digital I/O pin 6 - PWM enabled",
    },
    {
      id: "d6",
      type: "target",
      position: Position.Right,
      label: "D6",
      dataType: "value",
      offsetPercentage: 60,
      description: "Digital I/O pin 6 - PWM enabled",
    },
    {
      id: "d7",
      type: "source",
      position: Position.Right,
      label: "D7",
      dataType: "value",
      offsetPercentage: 55,
      description: "Digital I/O pin 7",
    },
    {
      id: "d7",
      type: "target",
      position: Position.Right,
      label: "D7",
      dataType: "value",
      offsetPercentage: 55,
      description: "Digital I/O pin 7",
    },
    {
      id: "d8",
      type: "source",
      position: Position.Right,
      label: "D8",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O pin 8",
    },
    {
      id: "d8",
      type: "target",
      position: Position.Right,
      label: "D8",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O pin 8",
    },
    {
      id: "d9",
      type: "source",
      position: Position.Right,
      label: "D9",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O pin 9 - PWM enabled",
    },
    {
      id: "d9",
      type: "target",
      position: Position.Right,
      label: "D9",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O pin 9 - PWM enabled",
    },
    {
      id: "d10",
      type: "source",
      position: Position.Right,
      label: "D10",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O pin 10 - PWM enabled, SPI SS",
    },
    {
      id: "d10",
      type: "target",
      position: Position.Right,
      label: "D10",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O pin 10 - PWM enabled, SPI SS",
    },
    {
      id: "d11",
      type: "source",
      position: Position.Right,
      label: "D11",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O pin 11 - PWM enabled, SPI MOSI",
    },
    {
      id: "d11",
      type: "target",
      position: Position.Right,
      label: "D11",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O pin 11 - PWM enabled, SPI MOSI",
    },
    {
      id: "d12",
      type: "source",
      position: Position.Right,
      label: "D12",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O pin 12 - SPI MISO",
    },
    {
      id: "d12",
      type: "target",
      position: Position.Right,
      label: "D12",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O pin 12 - SPI MISO",
    },
    {
      id: "d13",
      type: "source",
      position: Position.Right,
      label: "D13",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O pin 13 - built-in LED, SPI SCK",
    },
    {
      id: "d13",
      type: "target",
      position: Position.Right,
      label: "D13",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O pin 13 - built-in LED, SPI SCK",
    },
  ],
  width: 364,
  height: 400,
};

/**
 * ESP32 DevKit Node Configuration
 */
export const esp32NodeConfig: NodeConfig = {
  type: "esp32",
  title: "ESP32 DevKit",
  subtitle: "WiFi Microcontroller",
  icon: Cpu,
  handles: [
    // Power pins (Left side - top)
    {
      id: "3v3",
      type: "source",
      position: Position.Left,
      label: "3.3V",
      dataType: "value",
      offsetPercentage: 5,
      description: "Regulated 3.3V power output",
    },
    {
      id: "3v3",
      type: "target",
      position: Position.Left,
      label: "3.3V",
      dataType: "value",
      offsetPercentage: 5,
      description: "Regulated 3.3V power output",
    },
    {
      id: "gnd1",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 10,
      description: "Ground reference",
    },
    {
      id: "gnd1",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 10,
      description: "Ground reference",
    },

    // GPIO pins (Left side)
    {
      id: "gpio15",
      type: "source",
      position: Position.Left,
      label: "GPIO15",
      dataType: "value",
      offsetPercentage: 15,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio15",
      type: "target",
      position: Position.Left,
      label: "GPIO15",
      dataType: "value",
      offsetPercentage: 15,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio2",
      type: "source",
      position: Position.Left,
      label: "GPIO2",
      dataType: "value",
      offsetPercentage: 20,
      description: "Digital I/O, PWM, ADC2, built-in LED",
    },
    {
      id: "gpio2",
      type: "target",
      position: Position.Left,
      label: "GPIO2",
      dataType: "value",
      offsetPercentage: 20,
      description: "Digital I/O, PWM, ADC2, built-in LED",
    },
    {
      id: "gpio0",
      type: "source",
      position: Position.Left,
      label: "GPIO0",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio0",
      type: "target",
      position: Position.Left,
      label: "GPIO0",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio4",
      type: "source",
      position: Position.Left,
      label: "GPIO4",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio4",
      type: "target",
      position: Position.Left,
      label: "GPIO4",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio16",
      type: "source",
      position: Position.Left,
      label: "GPIO16",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O, PWM",
    },
    {
      id: "gpio16",
      type: "target",
      position: Position.Left,
      label: "GPIO16",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O, PWM",
    },
    {
      id: "gpio17",
      type: "source",
      position: Position.Left,
      label: "GPIO17",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O, PWM",
    },
    {
      id: "gpio17",
      type: "target",
      position: Position.Left,
      label: "GPIO17",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O, PWM",
    },
    {
      id: "gpio5",
      type: "source",
      position: Position.Left,
      label: "GPIO5",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O, PWM, SPI SS",
    },
    {
      id: "gpio5",
      type: "target",
      position: Position.Left,
      label: "GPIO5",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O, PWM, SPI SS",
    },
    {
      id: "gpio18",
      type: "source",
      position: Position.Left,
      label: "GPIO18",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O, PWM, SPI SCK",
    },
    {
      id: "gpio18",
      type: "target",
      position: Position.Left,
      label: "GPIO18",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O, PWM, SPI SCK",
    },
    {
      id: "gpio19",
      type: "source",
      position: Position.Left,
      label: "GPIO19",
      dataType: "value",
      offsetPercentage: 55,
      description: "Digital I/O, PWM, SPI MISO",
    },
    {
      id: "gpio19",
      type: "target",
      position: Position.Left,
      label: "GPIO19",
      dataType: "value",
      offsetPercentage: 55,
      description: "Digital I/O, PWM, SPI MISO",
    },
    {
      id: "gnd2",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 60,
      description: "Ground reference",
    },
    {
      id: "gnd2",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 60,
      description: "Ground reference",
    },
    {
      id: "gpio21",
      type: "source",
      position: Position.Left,
      label: "GPIO21",
      dataType: "value",
      offsetPercentage: 65,
      description: "Digital I/O, PWM, I2C SDA",
    },
    {
      id: "gpio21",
      type: "target",
      position: Position.Left,
      label: "GPIO21",
      dataType: "value",
      offsetPercentage: 65,
      description: "Digital I/O, PWM, I2C SDA",
    },
    {
      id: "gpio3",
      type: "source",
      position: Position.Left,
      label: "GPIO3",
      dataType: "value",
      offsetPercentage: 70,
      description: "Digital I/O, UART RX",
    },
    {
      id: "gpio3",
      type: "target",
      position: Position.Left,
      label: "GPIO3",
      dataType: "value",
      offsetPercentage: 70,
      description: "Digital I/O, UART RX",
    },
    {
      id: "gpio1",
      type: "source",
      position: Position.Left,
      label: "GPIO1",
      dataType: "value",
      offsetPercentage: 75,
      description: "Digital I/O, UART TX",
    },
    {
      id: "gpio1",
      type: "target",
      position: Position.Left,
      label: "GPIO1",
      dataType: "value",
      offsetPercentage: 75,
      description: "Digital I/O, UART TX",
    },
    {
      id: "gpio22",
      type: "source",
      position: Position.Left,
      label: "GPIO22",
      dataType: "value",
      offsetPercentage: 80,
      description: "Digital I/O, PWM, I2C SCL",
    },
    {
      id: "gpio22",
      type: "target",
      position: Position.Left,
      label: "GPIO22",
      dataType: "value",
      offsetPercentage: 80,
      description: "Digital I/O, PWM, I2C SCL",
    },
    {
      id: "gpio23",
      type: "source",
      position: Position.Left,
      label: "GPIO23",
      dataType: "value",
      offsetPercentage: 85,
      description: "Digital I/O, PWM, SPI MOSI",
    },
    {
      id: "gpio23",
      type: "target",
      position: Position.Left,
      label: "GPIO23",
      dataType: "value",
      offsetPercentage: 85,
      description: "Digital I/O, PWM, SPI MOSI",
    },

    // Right side pins
    {
      id: "vin",
      type: "source",
      position: Position.Right,
      label: "VIN",
      dataType: "value",
      offsetPercentage: 5,
      description: "External power input (5-12V)",
    },
    {
      id: "vin",
      type: "target",
      position: Position.Right,
      label: "VIN",
      dataType: "value",
      offsetPercentage: 5,
      description: "External power input (5-12V)",
    },
    {
      id: "gnd3",
      type: "source",
      position: Position.Right,
      label: "GND",
      dataType: "value",
      offsetPercentage: 10,
      description: "Ground reference",
    },
    {
      id: "gnd3",
      type: "target",
      position: Position.Right,
      label: "GND",
      dataType: "value",
      offsetPercentage: 10,
      description: "Ground reference",
    },
    {
      id: "gpio13",
      type: "source",
      position: Position.Right,
      label: "GPIO13",
      dataType: "value",
      offsetPercentage: 15,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio13",
      type: "target",
      position: Position.Right,
      label: "GPIO13",
      dataType: "value",
      offsetPercentage: 15,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio12",
      type: "source",
      position: Position.Right,
      label: "GPIO12",
      dataType: "value",
      offsetPercentage: 20,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio12",
      type: "target",
      position: Position.Right,
      label: "GPIO12",
      dataType: "value",
      offsetPercentage: 20,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio14",
      type: "source",
      position: Position.Right,
      label: "GPIO14",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio14",
      type: "target",
      position: Position.Right,
      label: "GPIO14",
      dataType: "value",
      offsetPercentage: 25,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio27",
      type: "source",
      position: Position.Right,
      label: "GPIO27",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio27",
      type: "target",
      position: Position.Right,
      label: "GPIO27",
      dataType: "value",
      offsetPercentage: 30,
      description: "Digital I/O, PWM, ADC2",
    },
    {
      id: "gpio26",
      type: "source",
      position: Position.Right,
      label: "GPIO26",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O, PWM, ADC2, DAC2",
    },
    {
      id: "gpio26",
      type: "target",
      position: Position.Right,
      label: "GPIO26",
      dataType: "value",
      offsetPercentage: 35,
      description: "Digital I/O, PWM, ADC2, DAC2",
    },
    {
      id: "gpio25",
      type: "source",
      position: Position.Right,
      label: "GPIO25",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O, PWM, ADC2, DAC1",
    },
    {
      id: "gpio25",
      type: "target",
      position: Position.Right,
      label: "GPIO25",
      dataType: "value",
      offsetPercentage: 40,
      description: "Digital I/O, PWM, ADC2, DAC1",
    },
    {
      id: "gpio33",
      type: "source",
      position: Position.Right,
      label: "GPIO33",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O, PWM, ADC1",
    },
    {
      id: "gpio33",
      type: "target",
      position: Position.Right,
      label: "GPIO33",
      dataType: "value",
      offsetPercentage: 45,
      description: "Digital I/O, PWM, ADC1",
    },
    {
      id: "gpio32",
      type: "source",
      position: Position.Right,
      label: "GPIO32",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O, PWM, ADC1",
    },
    {
      id: "gpio32",
      type: "target",
      position: Position.Right,
      label: "GPIO32",
      dataType: "value",
      offsetPercentage: 50,
      description: "Digital I/O, PWM, ADC1",
    },
    {
      id: "gpio35",
      type: "source",
      position: Position.Right,
      label: "GPIO35",
      dataType: "value",
      offsetPercentage: 55,
      description: "Input only, ADC1",
    },
    {
      id: "gpio35",
      type: "target",
      position: Position.Right,
      label: "GPIO35",
      dataType: "value",
      offsetPercentage: 55,
      description: "Input only, ADC1",
    },
    {
      id: "gpio34",
      type: "source",
      position: Position.Right,
      label: "GPIO34",
      dataType: "value",
      offsetPercentage: 60,
      description: "Input only, ADC1",
    },
    {
      id: "gpio34",
      type: "target",
      position: Position.Right,
      label: "GPIO34",
      dataType: "value",
      offsetPercentage: 60,
      description: "Input only, ADC1",
    },
    {
      id: "gpio39",
      type: "source",
      position: Position.Right,
      label: "GPIO39",
      dataType: "value",
      offsetPercentage: 65,
      description: "Input only, ADC1",
    },
    {
      id: "gpio39",
      type: "target",
      position: Position.Right,
      label: "GPIO39",
      dataType: "value",
      offsetPercentage: 65,
      description: "Input only, ADC1",
    },
    {
      id: "gpio36",
      type: "source",
      position: Position.Right,
      label: "GPIO36",
      dataType: "value",
      offsetPercentage: 70,
      description: "Input only, ADC1",
    },
    {
      id: "gpio36",
      type: "target",
      position: Position.Right,
      label: "GPIO36",
      dataType: "value",
      offsetPercentage: 70,
      description: "Input only, ADC1",
    },
    {
      id: "en",
      type: "source",
      position: Position.Right,
      label: "EN",
      dataType: "value",
      offsetPercentage: 75,
      description: "Enable pin (chip reset)",
    },
    {
      id: "en",
      type: "target",
      position: Position.Right,
      label: "EN",
      dataType: "value",
      offsetPercentage: 75,
      description: "Enable pin (chip reset)",
    },
  ],
  width: 400,
  height: 480,
};

/**
 * RGB LED Node Configuration
 */
export const rgbLedNodeConfig: NodeConfig = {
  type: "rgb-led",
  title: "RGB LED",
  subtitle: "Multi-color LED",
  icon: Lightbulb,
  handles: [
    {
      id: "r",
      type: "source",
      position: Position.Left,
      label: "R",
      dataType: "value",
      offsetPercentage: 25,
      description: "Red channel (PWM)",
    },
    {
      id: "r",
      type: "target",
      position: Position.Left,
      label: "R",
      dataType: "value",
      offsetPercentage: 25,
      description: "Red channel (PWM)",
    },
    {
      id: "g",
      type: "source",
      position: Position.Left,
      label: "G",
      dataType: "value",
      offsetPercentage: 50,
      description: "Green channel (PWM)",
    },
    {
      id: "g",
      type: "target",
      position: Position.Left,
      label: "G",
      dataType: "value",
      offsetPercentage: 50,
      description: "Green channel (PWM)",
    },
    {
      id: "b",
      type: "source",
      position: Position.Left,
      label: "B",
      dataType: "value",
      offsetPercentage: 75,
      description: "Blue channel (PWM)",
    },
    {
      id: "b",
      type: "target",
      position: Position.Left,
      label: "B",
      dataType: "value",
      offsetPercentage: 75,
      description: "Blue channel (PWM)",
    },
    {
      id: "cathode",
      type: "source",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 50,
      description: "Common cathode (ground)",
    },
    {
      id: "cathode",
      type: "target",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 50,
      description: "Common cathode (ground)",
    },
  ],
  width: 200,
  height: 150,
};

/**
 * Buzzer Node Configuration
 */
export const buzzerNodeConfig: NodeConfig = {
  type: "buzzer",
  title: "Buzzer",
  subtitle: "Sound Output",
  icon: Volume2,
  handles: [
    {
      id: "positive",
      type: "source",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 40,
      description: "Positive terminal",
    },
    {
      id: "positive",
      type: "target",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 40,
      description: "Positive terminal",
    },
    {
      id: "ground",
      type: "source",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 40,
      description: "Ground",
    },
    {
      id: "ground",
      type: "target",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 40,
      description: "Ground",
    },
  ],
  width: 180,
  height: 140,
};

/**
 * DC Motor Node Configuration
 */
export const dcMotorNodeConfig: NodeConfig = {
  type: "dc-motor",
  title: "DC Motor",
  subtitle: "Rotation Motor",
  icon: Fan,
  handles: [
    {
      id: "positive",
      type: "source",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 40,
      description: "Positive terminal",
    },
    {
      id: "positive",
      type: "target",
      position: Position.Left,
      label: "+",
      dataType: "value",
      offsetPercentage: 40,
      description: "Positive terminal",
    },
    {
      id: "negative",
      type: "source",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 40,
      description: "Negative terminal",
    },
    {
      id: "negative",
      type: "target",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 40,
      description: "Negative terminal",
    },
  ],
  width: 180,
  height: 160,
};

/**
 * Servo Motor Node Configuration
 */
export const servoNodeConfig: NodeConfig = {
  type: "servo",
  title: "Servo Motor",
  subtitle: "Position Control",
  icon: Gauge,
  handles: [
    {
      id: "vcc",
      type: "source",
      position: Position.Left,
      label: "VCC",
      dataType: "value",
      offsetPercentage: 30,
      description: "Power supply (4.8-6V)",
    },
    {
      id: "vcc",
      type: "target",
      position: Position.Left,
      label: "VCC",
      dataType: "value",
      offsetPercentage: 30,
      description: "Power supply (4.8-6V)",
    },
    {
      id: "gnd",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 70,
      description: "Ground",
    },
    {
      id: "gnd",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 70,
      description: "Ground",
    },
    {
      id: "signal",
      type: "source",
      position: Position.Right,
      label: "SIG",
      dataType: "value",
      offsetPercentage: 50,
      description: "PWM control signal",
    },
    {
      id: "signal",
      type: "target",
      position: Position.Right,
      label: "SIG",
      dataType: "value",
      offsetPercentage: 50,
      description: "PWM control signal",
    },
  ],
  width: 200,
  height: 180,
};

/**
 * LCD 16x2 Node Configuration
 */
export const lcd16x2NodeConfig: NodeConfig = {
  type: "lcd16x2",
  title: "LCD 16x2",
  subtitle: "Character Display",
  icon: Monitor,
  handles: [
    {
      id: "vcc",
      type: "source",
      position: Position.Left,
      label: "VCC",
      dataType: "value",
      offsetPercentage: 40,
      description: "Power supply (5V)",
    },
    {
      id: "vcc",
      type: "target",
      position: Position.Left,
      label: "VCC",
      dataType: "value",
      offsetPercentage: 40,
      description: "Power supply (5V)",
    },
    {
      id: "gnd",
      type: "source",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 60,
      description: "Ground",
    },
    {
      id: "gnd",
      type: "target",
      position: Position.Left,
      label: "GND",
      dataType: "value",
      offsetPercentage: 60,
      description: "Ground",
    },
  ],
  width: 300,
  height: 160,
};

/**
 * 7-Segment Display Node Configuration
 */
export const sevenSegmentNodeConfig: NodeConfig = {
  type: "seven-segment",
  title: "7-Segment Display",
  subtitle: "Numeric Display",
  icon: Hash,
  handles: [
    {
      id: "a",
      type: "source",
      position: Position.Left,
      label: "A",
      dataType: "value",
      offsetPercentage: 10,
      description: "Segment A (top)",
    },
    {
      id: "a",
      type: "target",
      position: Position.Left,
      label: "A",
      dataType: "value",
      offsetPercentage: 10,
      description: "Segment A (top)",
    },
    {
      id: "b",
      type: "source",
      position: Position.Left,
      label: "B",
      dataType: "value",
      offsetPercentage: 20,
      description: "Segment B (top right)",
    },
    {
      id: "b",
      type: "target",
      position: Position.Left,
      label: "B",
      dataType: "value",
      offsetPercentage: 20,
      description: "Segment B (top right)",
    },
    {
      id: "c",
      type: "source",
      position: Position.Left,
      label: "C",
      dataType: "value",
      offsetPercentage: 30,
      description: "Segment C (bottom right)",
    },
    {
      id: "c",
      type: "target",
      position: Position.Left,
      label: "C",
      dataType: "value",
      offsetPercentage: 30,
      description: "Segment C (bottom right)",
    },
    {
      id: "d",
      type: "source",
      position: Position.Left,
      label: "D",
      dataType: "value",
      offsetPercentage: 40,
      description: "Segment D (bottom)",
    },
    {
      id: "d",
      type: "target",
      position: Position.Left,
      label: "D",
      dataType: "value",
      offsetPercentage: 40,
      description: "Segment D (bottom)",
    },
    {
      id: "e",
      type: "source",
      position: Position.Left,
      label: "E",
      dataType: "value",
      offsetPercentage: 50,
      description: "Segment E (bottom left)",
    },
    {
      id: "e",
      type: "target",
      position: Position.Left,
      label: "E",
      dataType: "value",
      offsetPercentage: 50,
      description: "Segment E (bottom left)",
    },
    {
      id: "f",
      type: "source",
      position: Position.Left,
      label: "F",
      dataType: "value",
      offsetPercentage: 60,
      description: "Segment F (top left)",
    },
    {
      id: "f",
      type: "target",
      position: Position.Left,
      label: "F",
      dataType: "value",
      offsetPercentage: 60,
      description: "Segment F (top left)",
    },
    {
      id: "g",
      type: "source",
      position: Position.Left,
      label: "G",
      dataType: "value",
      offsetPercentage: 70,
      description: "Segment G (middle)",
    },
    {
      id: "g",
      type: "target",
      position: Position.Left,
      label: "G",
      dataType: "value",
      offsetPercentage: 70,
      description: "Segment G (middle)",
    },
    {
      id: "dp",
      type: "source",
      position: Position.Left,
      label: "DP",
      dataType: "value",
      offsetPercentage: 80,
      description: "Decimal point",
    },
    {
      id: "dp",
      type: "target",
      position: Position.Left,
      label: "DP",
      dataType: "value",
      offsetPercentage: 80,
      description: "Decimal point",
    },
    {
      id: "cathode",
      type: "source",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 50,
      description: "Common cathode (ground)",
    },
    {
      id: "cathode",
      type: "target",
      position: Position.Right,
      label: "−",
      dataType: "value",
      offsetPercentage: 50,
      description: "Common cathode (ground)",
    },
  ],
  width: 200,
  height: 220,
};

/**
 * Registry of all node configurations
 */
export const nodeConfigs: Record<string, NodeConfig> = {
  battery: batteryNodeConfig,
  led: ledNodeConfig,
  button: buttonNodeConfig,
  "arduino-uno": arduinoUnoNodeConfig,
  esp32: esp32NodeConfig,
  "rgb-led": rgbLedNodeConfig,
  buzzer: buzzerNodeConfig,
  "dc-motor": dcMotorNodeConfig,
  servo: servoNodeConfig,
  lcd16x2: lcd16x2NodeConfig,
  "seven-segment": sevenSegmentNodeConfig,
};

/**
 * Get configuration for a specific node type
 */
export function getNodeConfig(type: string): NodeConfig | undefined {
  return nodeConfigs[type];
}
